[package]
name = "Diplom"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.5", features = ["runtime-actix-rustls", "macros", "postgres"] }
bcrypt = "0.11"
actix-rt = "2"
dotenv = "0.15"

